name: Release

on:
  workflow_run:  # zizmor: ignore[dangerous-triggers]
    workflows:
      - "Build and Test"
    branches:
      - main
    types:
      - completed

concurrency:
  group: release-${{ github.event.workflow_run.id }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish GitHub Release
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      PROG: systemd-if
      OIDC_ISSUER: https://token.actions.githubusercontent.com
      NFPM_URL: https://github.com/goreleaser/nfpm
      DIST: dist

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
      - name: Download artifact from the triggering Build run
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.PROG }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ env.DIST }}
          github-token: ${{ github.token }}

      - name: Get next version
        id: next
        run: |
          chmod +x "${DIST}/${PROG}"
          VERSION=$("${DIST}/${PROG}" --version)
          echo "version=${VERSION}" | tee --append "${GITHUB_OUTPUT}"

      - name: Get build utilities release version
        id: version
        run: |
          read -r COSIGN_VERSION < "${GITHUB_WORKSPACE}/.cosign-version"
          echo "cosign=${COSIGN_VERSION}" | tee --append "${GITHUB_OUTPUT}"
          read -r NFPM_VERSION < "${GITHUB_WORKSPACE}/.nfpm-version"
          echo "nfpm=${NFPM_VERSION}" | tee --append "${GITHUB_OUTPUT}"

      - name: Install Cosign ${{ steps.cosign.outputs.version }}
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: ${{ steps.version.outputs.cosign }}

      - name: Download nFPM checksums
        id: nfpm_checksums
        run: |
          SIGSTORE_FILE="${CHECKSUMS_FILE}.sigstore.json"
          curl --fail --show-error --silent --location --remote-name \
            "${NFPM_URL}/releases/download/v${NFPM_VERSION}/${SIGSTORE_FILE}"
          echo "sigstore=${SIGSTORE_FILE}" | tee --append "${GITHUB_OUTPUT}"
          curl --fail --show-error --silent --location --remote-name \
            "${NFPM_URL}/releases/download/v${NFPM_VERSION}/${CHECKSUMS_FILE}"
          echo "file=${CHECKSUMS_FILE}" | tee --append "${GITHUB_OUTPUT}"
        env:
          CHECKSUMS_FILE: checksums.txt
          NFPM_VERSION: ${{ steps.version.outputs.nfpm }}

      - name: Verify nFPM checksums
        run: |
          cosign verify-blob \
            --certificate-identity "${NFPM_URL}/.github/workflows/release.yml@refs/tags/v${NFPM_VERSION}" \
            --certificate-oidc-issuer "${OIDC_ISSUER}" \
            --bundle "${SIGSTORE_FILE}" \
            "${CHECKSUMS_FILE}"
        env:
          CHECKSUMS_FILE: ${{ steps.nfpm_checksums.outputs.file }}
          SIGSTORE_FILE: ${{ steps.nfpm_checksums.outputs.sigstore }}
          NFPM_VERSION: ${{ steps.version.outputs.nfpm }}

      - name: Get architecture
        id: ubuntu
        run: |
          ARCH=$(dpkg --print-architecture)
          echo "arch=${ARCH}" | tee --append "${GITHUB_OUTPUT}"

      - name: Download nFPM ${{ steps.version.outputs.nfpm }} ${{ steps.ubuntu.outputs.arch }}
        id: nfpm
        run: |
          curl --fail --show-error --silent --location --remote-name \
            "${NFPM_URL}/releases/download/v${NFPM_VERSION}/${FILE}"
          echo "file=${FILE}" | tee --append "${GITHUB_OUTPUT}"
        env:
          FILE: nfpm_${{ steps.version.outputs.nfpm }}_${{ steps.ubuntu.outputs.arch }}.deb
          NFPM_VERSION: ${{ steps.version.outputs.nfpm }}

      - name: Verify nFPM checksum
        run: sha256sum --ignore-missing --check "${CHECKSUMS_FILE}"
        env:
          CHECKSUMS_FILE: ${{ steps.nfpm_checksums.outputs.file }}

      - name: Install nFPM
        run: sudo dpkg --no-triggers --install "${FILE}"
        env:
          FILE: ${{ steps.nfpm.outputs.file }}

      - name: Create packages
        run: |
          old_dir="$(pwd)"
          cd "${DIST}"
          for pkg in apk archlinux deb ipk rpm; do
            nfpm package --packager "${pkg}"
          done
          rm --force -- LICENSE nfpm.yaml "${PROG}"
          cd "${old_dir}"
        env:
          VERSION: ${{ steps.next.outputs.version }}

      - name: Create and sign checksums
        id: file
        run: |
          old_dir="$(pwd)"
          cd "${DIST}"
          find . -type f -print0 |
            sort --zero-terminated |
            xargs --null --max-args=1 basename |
            xargs "${CHECKSUM_FILE##*.}sum" |
            tee "../${CHECKSUM_FILE}"
          mv --force --verbose "../${CHECKSUM_FILE}" .
          SIGSTORE_FILE="${CHECKSUM_FILE}.sigstore.json"
          cosign sign-blob --yes --bundle "${SIGSTORE_FILE}" "${CHECKSUM_FILE}"
          cd "${old_dir}"
          echo "checksum=${CHECKSUM_FILE}" | tee --append "${GITHUB_OUTPUT}"
          echo "sigstore=${SIGSTORE_FILE}" | tee --append "${GITHUB_OUTPUT}"
        env:
          CHECKSUM_FILE: CHECKSUM_${{ steps.next.outputs.version }}.sha256

      - name: Verify checksums
        run: |
          old_dir="$(pwd)"
          cd "${DIST}"
          cosign verify-blob \
            --certificate-identity "${GITHUB_SERVER_URL}/${GITHUB_WORKFLOW_REF}" \
            --certificate-oidc-issuer "${OIDC_ISSUER}" \
            --bundle "${SIGSTORE_FILE}" \
            "${CHECKSUM_FILE}"
          cd "${old_dir}"
        env:
          CHECKSUM_FILE: ${{ steps.file.outputs.checksum }}
          SIGSTORE_FILE: ${{ steps.file.outputs.sigstore }}

      - name: Create GitHub Release and upload assets  # zizmor: ignore[superfluous-actions]
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          tag_name: v${{ steps.next.outputs.version }}
          target_commitish: ${{ github.event.workflow_run.head_sha }}
          generate_release_notes: true
          files: |
            ${{ env.DIST }}/${{ steps.file.outputs.checksum }}
            ${{ env.DIST }}/${{ steps.file.outputs.sigstore }}
            ${{ env.DIST }}/${{ env.PROG }}-${{ steps.next.outputs.version }}*-x86_64.pkg.tar.zst
            ${{ env.DIST }}/${{ env.PROG }}-${{ steps.next.outputs.version }}*.x86_64.rpm
            ${{ env.DIST }}/${{ env.PROG }}_${{ steps.next.outputs.version }}_amd64.deb
            ${{ env.DIST }}/${{ env.PROG }}_${{ steps.next.outputs.version }}_x86_64.apk
            ${{ env.DIST }}/${{ env.PROG }}_${{ steps.next.outputs.version }}_x86_64.ipk
